### ISSUE TITLE
Fix unsorted leaderboard on non-Firefox browsers

### ISSUE THREAD

**Issue by anirudhRowjee** [acmpesuecc/HackNight-LeaderBoard#2]
The leaderboard isn't sorted on any browser other than Firefox.
Implement a solution which ensures it's sorted across all browsers.

**Comment by Smuzzy-waiii** [comment]
Can i get assigned to this?

**Comment by karunakc** [comment]
> Can i get assigned to this?

Sure!

**Comment by PhoenixFlame101** [comment]
Hey can I be assigned this?
